server:
  port: 18113
  servlet:
    application-display-name: ribion-demo-learn-name
spring:
  application:
    #这个名字是在注册中心显示的名字
    name: ribbon-demo-learn-name

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:18100/eureka/

