server:
  port: 18112
  servlet:
    application-display-name: ribion-learn-name
spring:
  application:
    #这个名字是在注册中心显示的名字
    name: ribbon-learn-name
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: true

eureka:
  client:
    service-url:
      #注册中心地址
      defaultZone: http://localhost:18100/eureka/

